// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: bidrectional_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_bidrectional_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bidrectional_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_bidrectional_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_bidrectional_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bidrectional_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_bidrectional_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_bidrectional_stream_proto protoreflect.FileDescriptor

const file_bidrectional_stream_proto_rawDesc = "" +
	"\n" +
	"\x19bidrectional_stream.proto\"#\n" +
	"\rStreamRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\":\n" +
	"\x0eStreamResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2@\n" +
	"\rStreamService\x12/\n" +
	"\x06Record\x12\x0e.StreamRequest\x1a\x0f.StreamResponse\"\x00(\x010\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_bidrectional_stream_proto_rawDescOnce sync.Once
	file_bidrectional_stream_proto_rawDescData []byte
)

func file_bidrectional_stream_proto_rawDescGZIP() []byte {
	file_bidrectional_stream_proto_rawDescOnce.Do(func() {
		file_bidrectional_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bidrectional_stream_proto_rawDesc), len(file_bidrectional_stream_proto_rawDesc)))
	})
	return file_bidrectional_stream_proto_rawDescData
}

var file_bidrectional_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bidrectional_stream_proto_goTypes = []any{
	(*StreamRequest)(nil),  // 0: StreamRequest
	(*StreamResponse)(nil), // 1: StreamResponse
}
var file_bidrectional_stream_proto_depIdxs = []int32{
	0, // 0: StreamService.Record:input_type -> StreamRequest
	1, // 1: StreamService.Record:output_type -> StreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bidrectional_stream_proto_init() }
func file_bidrectional_stream_proto_init() {
	if File_bidrectional_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bidrectional_stream_proto_rawDesc), len(file_bidrectional_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidrectional_stream_proto_goTypes,
		DependencyIndexes: file_bidrectional_stream_proto_depIdxs,
		MessageInfos:      file_bidrectional_stream_proto_msgTypes,
	}.Build()
	File_bidrectional_stream_proto = out.File
	file_bidrectional_stream_proto_goTypes = nil
	file_bidrectional_stream_proto_depIdxs = nil
}
